"""Test revision

Revision ID: 165133f4982e
Revises: 34bee96ebc79
Create Date: 2021-06-27 13:43:21.015681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165133f4982e'
down_revision = '34bee96ebc79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
