"""Add bot model

Revision ID: 34bee96ebc79
Revises: 51121e441570
Create Date: 2021-06-27 10:47:05.307384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bee96ebc79'
down_revision = '51121e441570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
