"""Added bot to account relationship

Revision ID: 4e46707b2f05
Revises: ecfe7280874c
Create Date: 2021-07-04 19:17:44.662937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e46707b2f05'
down_revision = 'ecfe7280874c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bot', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_column('bot', 'account_id')
    # ### end Alembic commands ###
