"""Add bot model

Revision ID: 51121e441570
Revises: 87ae81719c0a
Create Date: 2021-06-27 10:46:16.562370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51121e441570'
down_revision = '87ae81719c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_description'), 'bot', ['description'], unique=False)
    op.create_index(op.f('ix_bot_id'), 'bot', ['id'], unique=False)
    op.create_index(op.f('ix_bot_name'), 'bot', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_name'), table_name='bot')
    op.drop_index(op.f('ix_bot_id'), table_name='bot')
    op.drop_index(op.f('ix_bot_description'), table_name='bot')
    op.drop_table('bot')
    # ### end Alembic commands ###
