"""Added is_running column to Bot model

Revision ID: 5fdf55ca3000
Revises: 654a00c31c07
Create Date: 2021-07-03 22:21:02.082835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fdf55ca3000'
down_revision = '654a00c31c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('is_running', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot', 'is_running')
    # ### end Alembic commands ###
