"""Added profit fields to Bot model

Revision ID: 654a00c31c07
Revises: 750a02bc7d57
Create Date: 2021-07-02 23:34:25.726487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654a00c31c07'
down_revision = '750a02bc7d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot', sa.Column('profit_24h', sa.Numeric(), nullable=True))
    op.add_column('bot', sa.Column('profit_all_time', sa.Numeric(), nullable=True))
    op.drop_index('ix_bot_description', table_name='bot')
    op.drop_index('ix_bot_name', table_name='bot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bot_name', 'bot', ['name'], unique=False)
    op.create_index('ix_bot_description', 'bot', ['description'], unique=False)
    op.drop_column('bot', 'profit_all_time')
    op.drop_column('bot', 'profit_24h')
    # ### end Alembic commands ###
