"""Added strategy table

Revision ID: 6bf09e19ad93
Revises: 165133f4982e
Create Date: 2021-06-27 14:00:40.435771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf09e19ad93'
down_revision = '165133f4982e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_description'), 'strategy', ['description'], unique=False)
    op.create_index(op.f('ix_strategy_id'), 'strategy', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_name'), 'strategy', ['name'], unique=False)
    op.add_column('bot', sa.Column('strategy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bot', 'strategy', ['strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bot', type_='foreignkey')
    op.drop_column('bot', 'strategy_id')
    op.drop_index(op.f('ix_strategy_name'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_description'), table_name='strategy')
    op.drop_table('strategy')
    # ### end Alembic commands ###
