"""Added bot to account relationship

Revision ID: b9b19973bf23
Revises: 4e46707b2f05
Create Date: 2021-07-04 19:22:15.719858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b19973bf23'
down_revision = '4e46707b2f05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
