"""Added more fields to Accout model

Revision ID: ecfe7280874c
Revises: 2efe15bf7baa
Create Date: 2021-07-04 14:46:42.964806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfe7280874c'
down_revision = '2efe15bf7baa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('connected_at', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('connection_updated_at', sa.DateTime(), nullable=True))
    op.add_column('account', sa.Column('is_valid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'is_valid')
    op.drop_column('account', 'connection_updated_at')
    op.drop_column('account', 'connected_at')
    # ### end Alembic commands ###
