version: "3.7"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - ./signals_listener/env.env

  database:
    image: "postgres"
    env_file:
      - ./signals_listener/env.env
    volumes:
      - database-data:/var/lib/postgresql/data/

  signals-listener:
    build:
      context: signals_listener
      dockerfile: publisher.dockerfile
    env_file:
      - ./signals_listener/env.env
    depends_on:
      - database

volumes:
  database-data: