"""Added Exchange model

Revision ID: 00a37a693ca5
Revises: e9d4c28ec974
Create Date: 2021-09-07 01:30:43.881756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00a37a693ca5"
down_revision = "e9d4c28ec974"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
