"""Added UserExchange model

Revision ID: 0e00e61f671b
Revises: 3d7cd3cda5a0
Create Date: 2021-09-07 01:59:37.105248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e00e61f671b'
down_revision = '3d7cd3cda5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
