"""Added field exchange_order_id

Revision ID: 217db93e8ba5
Revises: 20faf9aaf90f
Create Date: 2021-10-24 04:16:54.532783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "217db93e8ba5"
down_revision = "20faf9aaf90f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("exchange_order_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "exchange_order_id")
    # ### end Alembic commands ###
