"""Added relationship between Exchange and UserExchange

Revision ID: 3c6ae9782717
Revises: 0044612b7f34
Create Date: 2021-10-09 14:29:06.893491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6ae9782717'
down_revision = '0044612b7f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
