"""Added DCA_Bot model

Revision ID: 57a74360a785
Revises: 8a5ef916e5ba
Create Date: 2021-09-11 12:47:54.647857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57a74360a785"
down_revision = "8a5ef916e5ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
