"""Provider_id in user

Revision ID: 684036a2c676
Revises: ed2299553ae9
Create Date: 2021-10-31 18:31:21.415703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "684036a2c676"
down_revision = "ed2299553ae9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("provider_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "provider_id")
    # ### end Alembic commands ###
