"""Added DCA_Bot model

Revision ID: a3423a2ca38a
Revises: 57a74360a785
Create Date: 2021-09-11 12:50:51.988698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a3423a2ca38a"
down_revision = "57a74360a785"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dcabot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("required_balance", sa.Float(), nullable=True),
        sa.Column("base_coin", sa.String(), nullable=False),
        sa.Column("base_order_amount", sa.Float(), nullable=False),
        sa.Column("safety_order_amount", sa.Float(), nullable=False),
        sa.Column("max_safety_orders", sa.Integer(), nullable=False),
        sa.Column("max_active_safety_orders", sa.Integer(), nullable=False),
        sa.Column("safety_order_price_deviation_pct", sa.Float(), nullable=False),
        sa.Column("safety_order_price_deviation_scale", sa.Float(), nullable=False),
        sa.Column("allocated_funds", sa.Float(), nullable=True),
        sa.Column("trading_pairs", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("consider_overall_sentiment", sa.Boolean(), nullable=True),
        sa.Column("stop_loss_pct", sa.Float(), nullable=True),
        sa.Column("take_profit_pct", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("user_exchange_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_exchange_id"],
            ["userexchange.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dcabot_id"), "dcabot", ["id"], unique=False)
    op.create_index(op.f("ix_dcabot_name"), "dcabot", ["name"], unique=False)
    op.create_index(
        op.f("ix_dcabot_user_exchange_id"), "dcabot", ["user_exchange_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_dcabot_user_exchange_id"), table_name="dcabot")
    op.drop_index(op.f("ix_dcabot_name"), table_name="dcabot")
    op.drop_index(op.f("ix_dcabot_id"), table_name="dcabot")
    op.drop_table("dcabot")
    # ### end Alembic commands ###
