"""assets in userexchange

Revision ID: af709256ec9f
Revises: d3be155ba0a2
Create Date: 2021-10-27 05:20:00.435727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af709256ec9f"
down_revision = "d3be155ba0a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userexchange", sa.Column("assets", sa.ARRAY(sa.JSON()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userexchange", "assets")
    # ### end Alembic commands ###
