"""Added orders-deal relationship

Revision ID: b62cfa90cb12
Revises: 217db93e8ba5
Create Date: 2021-10-26 02:19:34.765403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b62cfa90cb12"
down_revision = "217db93e8ba5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
