"""Added orders-deal relationship

Revision ID: d3be155ba0a2
Revises: b62cfa90cb12
Create Date: 2021-10-26 02:44:29.898218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3be155ba0a2"
down_revision = "b62cfa90cb12"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
