"""Provider in user

Revision ID: ed2299553ae9
Revises: af709256ec9f
Create Date: 2021-10-31 18:25:23.830351

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ed2299553ae9"
down_revision = "af709256ec9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    providerenum = postgresql.ENUM("bearbounty", "google", name="providerenum")
    providerenum.create(op.get_bind())
    op.add_column(
        "user",
        sa.Column(
            "provider",
            sa.Enum("bearbounty", "google", name="providerenum"),
            nullable=True,
            server_default="bearbounty",
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "provider")
    # ### end Alembic commands ###
