"""Added is_running field in DCA_Bot model

Revision ID: ff28fd837777
Revises: a3423a2ca38a
Create Date: 2021-09-11 23:31:43.445460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff28fd837777"
down_revision = "a3423a2ca38a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dcabot", sa.Column("is_running", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dcabot", "is_running")
    # ### end Alembic commands ###
